sudo: false
language: node_js
node_js:
  - 16 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
before_install:
  - "npm install -g npm@latest"
install:
  - "npm i hexo-cli -g"
  - "npm i"
script:
  - hexo g # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
  